  <?php

  use yii\helpers\Html;
  use yii\bootstrap\Collapse;
  // use yii\grid\GridView;
  use kartik\grid\GridView;
  // use kartik\editable\Editable;
  /* a VER AINDA: OPÇÕES DE EXPORTAÇÃO DE DADOS PRA PDF E EXCELL
  $pdfHeader = 'header';
  $pdfFooter = 'footer';
  $title = '1';

  $defaultExportConfig = [
      // GridView::CSV => [
      //     'label' => 'CSV',
      //     'icon' => $isFa ? 'file-code-o' : 'floppy-open',
      //     'iconOptions' => ['class' => 'text-primary'],
      //     'showHeader' => true,
      //     'showPageSummary' => true,
      //     'showFooter' => true,
      //     'showCaption' => true,
      //     'filename' => Yii::t('kvgrid', 'grid-export'),
      //     'alertMsg' => Yii::t('kvgrid', 'The CSV export file will be generated for download.'),
      //     'options' => ['title' => Yii::t('kvgrid', 'Comma Separated Values')],
      //     'mime' => 'application/csv',
      //     'config' => [
      //         'colDelimiter' => ",",
      //         'rowDelimiter' => "\r\n",
      //     ]
      // ],
      GridView::EXCEL => [
          'label' => 'Para excel',
          'icon' => 'file-excel-o',
          'iconOptions' => ['class' => 'text-success'],
          'showHeader' => true,
          'showPageSummary' => true,
          'showFooter' => true,
          'showCaption' => true,
          'filename' => 'grid-export',
          'alertMsg' => 'The EXCEL export file will be generated for download.',
          'options' => ['title' => 'Microsoft Excel 95+'],
          'mime' => 'application/vnd.ms-excel',
          'config' => [
              'worksheet' => 'ExportWorksheet',
              'cssFile' => ''
          ]
      ],
      GridView::PDF => [
          'label' => 'PDF',
          'icon' => 'file-pdf-o',
          'iconOptions' => ['class' => 'text-danger'],
          'showHeader' => true,
          'showPageSummary' => true,
          'showFooter' => true,
          'showCaption' => true,
          'filename' => 'grid-export',
          'alertMsg' => 'The PDF export file will be generated for download.',
          'options' => ['title' => 'Portable Document Format'],
          'mime' => 'application/pdf',
          'config' => [
              'mode' => 'c',
              'format' => 'A4-L',
              'destination' => 'D',
              'marginTop' => 20,
              'marginBottom' => 20,
              'cssInline' => '.kv-wrap{padding:20px;}' .
                  '.kv-align-center{text-align:center;}' .
                  '.kv-align-left{text-align:left;}' .
                  '.kv-align-right{text-align:right;}' .
                  '.kv-align-top{vertical-align:top!important;}' .
                  '.kv-align-bottom{vertical-align:bottom!important;}' .
                  '.kv-align-middle{vertical-align:middle!important;}' .
                  '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
                  '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
                  '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
              'methods' => [
                  'SetHeader' => [
                      ['odd' => $pdfHeader, 'even' => $pdfHeader]
                  ],
                  'SetFooter' => [
                      ['odd' => $pdfFooter, 'even' => $pdfFooter]
                  ],
              ],
              'options' => [
                  'title' => $title,
                  'subject' =>  'PDF export generated by kartik-v/yii2-grid extension',
                  'keywords' => 'krajee, grid, export, yii2-grid, pdf'
              ],
              'contentBefore'=>'',
              'contentAfter'=>''
          ]
      ],
  ];
  */

  use yii\widgets\Pjax;

  /* ==================================================================================== */
  use app\models\Usuariopermutas as UP;


  // use yii\grid\GridView;
  /* @var $this yii\web\View */
  /* @var $searchModel app\models\ImovelpermutaSearch */
  /* @var $dataProvider yii\data\ActiveDataProvider */

  $json_imoveis = $this->context->get_content('http://www.jetimob.com/services/tZuuHuri8Q3ohAf7cvmMm8hTmWrXKJoEdes8ViSi/imoveis/',864000);

  $imoveis = json_decode($json_imoveis);
  $i = 1;
  $codigos = array();
  $bairros_imoveis = array();
  $tipos_imoveis = array();
  foreach ($imoveis as $e):
      $pos = strripos($e->observacoes, 'Permuta');
      if (!$pos === false) {
          $i++;
          $codigos[$e->codigo] = $e->codigo;
      }

      $bairros_imoveis[$e->endereco_bairro] = $e->endereco_bairro;
      $tipos_imoveis[$e->tipo] = $e->tipo;
      $tipos_imoveis[$e->subtipo] = $e->subtipo;

  endforeach;


  // if($_REQUEST ['ImovelpermutaSearch']['codigo'])
  //     $codigos[$_REQUEST['ImovelpermutaSearch']['codigo']] = $_REQUEST['ImovelpermutaSearch']['codigo'];
  //     // array_push($codigos,$_REQUEST['ImovelpermutaSearch']['codigo']);

  $codigos = array_filter(array_unique($codigos));


  $bairros_imoveis = array_filter(array_unique($bairros_imoveis));
  asort($bairros_imoveis);
  $tipos_imoveis = array_filter(array_unique($tipos_imoveis));
  asort($tipos_imoveis);

  $this->title = 'Imovel Permutas';
  $this->params['breadcrumbs'][] = $this->title;
  ?>
  <div class="imovel-permuta-index col-md-12">

      <h1><img src="<?=Yii::$app->homeUrl.'icones/imob_PC.png'?>" alt="" height="50" /><?= Html::encode($this->title) ?></h1>
      <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

      <div class="col-lg-3" style="">
      <?= $this->render('_search', [
          'model' => $searchModel,
          'codigos'=>$codigos,
          'bairros'=>$bairros_imoveis,
          'tipos'=>$tipos_imoveis,
      ]); ?>
      </div>
      <div class="col-lg-9">
      <p>
          <?= Html::a('Cadastrar Nova Permuta', ['create'], ['class' => 'btn btn-success','style'=>'float:right;margin-bottom:12px']) ?>
      </p>
      <hr>
      <?php Pjax::begin(); ?>
      <?= GridView::widget([
          'dataProvider' => $dataProvider,
          // 'floatHeader'=>true,
          // 'floatHeaderOptions'=>['scrollingTop'=>'50'],
          // 'filterModel' => $searchModel,
          // 'toolbar'=>[
          //     '{export}',
          //     '{toggleData}'
          // ],
          'columns' => [
              [
                  'class'=>'kartik\grid\ExpandRowColumn',
                  'width'=>'50px',
                  'value'=>function ($model, $key, $index, $column) {
                      return GridView::ROW_COLLAPSED;
                  },
                  'detail'=>function ($model, $key, $index, $column) {
                      return Yii::$app->controller->renderPartial('detalhes', [
                          'model'=>$model,
                          'codigo'=>$data->codigo
                      ]);
                  },
                  'headerOptions'=>['class'=>'kartik-sheet-style'] ,
                  'expandOneOnly'=>true
              ],
              // 'idimovel_permuta',
              // 'codigo',
              [
                  'attribute'=>'codigo',
                  'value'=> function($data){
                      return 'PIN-'.$data->codigo;
                  }
              ],
              'tipo:ntext',
              'dormitorios',
              'garagens',
              // 'area_privativa',
              [
                  'attribute'=>'area_privativa',
                  'value'=> function($data){
                      return number_format($data->area_total, 2, ',', '.').' m²';
                  }
              ],
              [
                  'attribute'=>'valor_minimo',
                  'value'=> function($data){
                      return 'R$ '.number_format($data->valor_minimo, 2, ',', '.');
                  }
              ],
              [
                  'header'=>'Ativo',
                  'attribute' => 'idimovel_permuta',
                  'value' => function($data){
                      $usuariopermutas = UP::find()->where(['permuta'=>$data->idimovel_permuta])->all();
                      if(count($usuariopermutas) >0 )
                          return 'SIM';
                      else
                          return 'Não';
                  },
              ],
              // [
              //     'value'=> function($data){
              //         return ''.
              //         'Elv.: '.$data->elevador.
              //         'Sac.: '.$data->sacada
              //         .'';
              //     }
              // ],
              // 'area_total',
              // 'bairros:ntext',
              // 'elevador',
              // 'sacada',
              // 'valor_maximo',
              // 'valor_minimo',
              // 'tipo_imovel',
              // [
              //     'attribute'=>'area_total',
              //     'value'=> function($data){
              //         return number_format($data->area_total, 2, ',', '.').' m²';
              //     },

              // ],
              // [
              //     'class' => 'kartik\grid\EditableColumn',
              //     'header'=>'Ver',
              //     'attribute' => 'idimovel_permuta',
              //     'value' => function($data){
              //         $usuariopermutas = UP::find()->where(['permuta'=>$data->idimovel_permuta])->all();
              //         if(count($usuariopermutas) >0 )
              //             return 'SIM';
              //         else
              //             return 'Não';

              //     },
              //     'editableOptions' => function ($data) {
              //             return [
              //                 'inputType' => Editable::INPUT_SWITCH,
              //                 'formOptions' => [ 'action' => [ 'editregistro'] ]
              //             ];
              //         }
              // ],
              ['class' => 'yii\grid\ActionColumn'],
          ],
          // 'exportConfig' => [
          //     GridView::CSV => ['label' => 'Save as Excell'],
          //         GridView::PDF => ['label'=>'PDF'],
          // ],
      ]); ?>
      <?php Pjax::end(); ?>
    </div>
  </div>
